import type { Session } from '@supabase/supabase-js'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabaseClient'
import { useMembershipStatus } from '../hooks/useMembershipStatus'

export default function AppHome({ session }: { session: Session }) {
  const { displayName, hasActiveMembership, periodLabel, appRole, loading } = useMembershipStatus(session)
  const isSuperAdmin = hasActiveMembership && appRole === 'super_admin'
  async function handleSignOut() { await supabase.auth.signOut() }
  return <div className="min-h-screen bg-canvas"><header className="border-b border-canvas-border bg-canvas-surface"><div className="mx-auto flex max-w-3xl items-center justify-between px-4 py-4"><span className="text-sm font-semibold text-ink">MUPSA Ekip Koordinasyon</span><button type="button" onClick={handleSignOut} className="text-sm font-medium text-ink-soft hover:text-ink">Çıkış yap</button></div></header><main className="mx-auto max-w-3xl px-4 py-8">{loading ? <p className="text-sm text-ink-soft">Yükleniyor…</p> : <><p className="text-sm text-ink-soft">Hoş geldin,</p><h1 className="mt-1 text-xl font-semibold text-ink">{displayName}</h1>{hasActiveMembership ? <div className="mt-6 rounded-lg border border-canvas-border bg-canvas-surface p-6 shadow-card"><p className="text-sm text-ink-soft">{periodLabel ? `Aktif dönem: ${periodLabel}` : 'Aktif dönem üyeliğin doğrulandı.'}</p><p className="mt-3 text-sm text-ink">Etkinlikler ve görevler bu alandan takip edilecek.</p></div> : <div className="mt-6 rounded-lg border border-accent/30 bg-accent-soft p-6"><p className="text-sm font-medium text-ink">Hesabın açık, ancak aktif dönem yetkin henüz tanımlanmamış.</p><p className="mt-2 text-sm text-ink-soft">Yönetim kurulu tarafından bu dönem için bir role atanman gerekiyor. Soruların için Bilişim Teknolojileri Koordinatörlüğü ile iletişime geç.</p></div>}{hasActiveMembership ? <Link to="/app/etkinlikler" className="mt-4 block rounded-lg border border-canvas-border bg-canvas-surface p-6 shadow-card hover:border-accent/40"><p className="text-sm font-semibold text-ink">Etkinlikler</p><p className="mt-2 text-sm text-ink-soft">Aktif dönemdeki etkinlikleri görüntüle.</p></Link> : null}{isSuperAdmin ? <Link to="/app/yonetim/uyeler" className="mt-4 block rounded-lg border border-canvas-border bg-canvas-surface p-6 shadow-card hover:border-accent/40"><p className="text-sm font-semibold text-ink">Ekip ve yetki yönetimi</p><p className="mt-2 text-sm text-ink-soft">Aktif dönemdeki koordinatörleri ve uygulama yetkilerini görüntüle.</p></Link> : null}</>}</main></div>
}
